# Generated by Django 3.2.25 on 2025-11-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tab', '0032_auto_20251110_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('herokunator_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.school')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_new_registrations', models.BooleanField(default=True)),
                ('allow_registration_edits', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('completion_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free_seed', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='registration.registration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.team')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('debater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.debater')),
                ('registration_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registration.registrationteam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.school')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.judge')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='registration.registration')),
            ],
        ),
    ]
