# Generated by Django 4.2.24 on 2026-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationconfig",
            name="disc_scratch_quantity",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="registrationconfig",
            name="disc_scratches_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registrationconfig",
            name="team_name_changes_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
