# Generated by Django 3.2.25 on 2026-05-03 18:53

from django.db import migrations, models
import mittab.apps.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registrationconfig_disc_scratch_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=500, validators=[mittab.apps.registration.models.validate_safe_url])),
                ('description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=500, validators=[mittab.apps.registration.models.validate_safe_url])),
                ('description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
