# Generated by Codex on 2026-05-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_infolink_registrationlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationConfirmationEmailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation_email_logs",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="registrationconfirmationemaillog",
            index=models.Index(
                fields=["registration", "sent_at"],
                name="registratio_registr_c8c8fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationconfirmationemaillog",
            index=models.Index(
                fields=["email", "sent_at"],
                name="registratio_email_f224f3_idx",
            ),
        ),
    ]
