FROM python:3.4

# install dependenices
RUN apt-get update && apt-get upgrade -y && \
  apt-get install sqlite3 && apt-get install -y vim

WORKDIR /var/www/tab
COPY requirements-speaks-dist.txt ./
RUN pip install -r requirements-speaks-dist.txt

COPY ./bin ./bin
COPY ./mittab ./mittab
