FROM python:3.7

# install dependenices
RUN apt-get update && apt-get upgrade -y && \
  apt-get install && apt-get install -y vim default-mysql-client
# sets up nodejs to install npm
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt-get install nodejs

WORKDIR /var/www/tab
COPY Pipfile ./
COPY Pipfile.lock ./
COPY package.json ./
COPY package-lock.json ./
RUN pip install pipenv
RUN pipenv install --deploy --system
RUN mkdir /var/tmp/django_cache

# setup django
COPY manage.py ./
COPY setup.py ./
COPY ./mittab ./mittab
COPY ./assets ./assets
COPY settings.yaml ./
