FROM python:3.10.16

# install dependenices
RUN apt-get update && apt-get upgrade -y && \
  apt-get install && apt-get install -y vim default-mysql-client
# sets up nodejs to install npm
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash
RUN apt-get install nodejs

WORKDIR /var/www/tab
COPY pyproject.toml ./
COPY uv.lock ./
COPY package.json ./
COPY package-lock.json ./
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"
ENV UV_PROJECT_ENVIRONMENT=/usr/local
RUN uv sync --frozen --no-dev --no-group docs
RUN mkdir /var/tmp/django_cache

# setup django
COPY manage.py ./
COPY ./mittab ./mittab
COPY ./assets ./assets
COPY ./settings ./settings
