FROM python:3.7

# install dependenices
RUN apt-get update && apt-get upgrade -y && \
  apt-get install

COPY Pipfile ./
COPY Pipfile.lock ./
RUN pip install pipenv
RUN pipenv install --deploy --system

# setup discord
COPY start_discord.py ./
COPY ./mit_tab_bot ./