# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 15:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='ballot_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
