# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 19:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debater',
            name='provider',
        ),
    ]
