# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_auto_20180226_1827'),
        ('tab', '0003_auto_20180226_1937'),
    ]

    operations = [
    ]
