# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('rank', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='rank',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
