# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0004_merge'),
        ('tab', '0002_judge_ballot_code'),
    ]

    operations = [
    ]
