# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0005_auto_20180328_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomgroup',
            name='rank',
        ),
        migrations.AddField(
            model_name='judge',
            name='room_group_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_group_priority', to='tab.RoomGroup'),
        ),
        migrations.AddField(
            model_name='room',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='tab.RoomGroup'),
        ),
        migrations.AddField(
            model_name='team',
            name='room_group_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_group_priorty', to='tab.RoomGroup'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rank',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='round',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tab.Room'),
        ),
    ]
