# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0005_auto_20180328_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tab.RoomGroup'),
        ),
    ]
