# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_room_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tab.RoomGroup'),
        ),
    ]
