# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_auto_20180409_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomgroup',
            old_name='checked_in',
            new_name='unavailable',
        ),
    ]
