# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tab', '0007_auto_20190505_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_tab.debater_set+',
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='debater',
            name='tiebreaker',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_tab.team_set+',
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='team',
            name='tiebreaker',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
