# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_auto_20180227_0142'),
        ('tab', '0007_auto_20180409_2036'),
    ]

    operations = [
    ]
