# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0007_auto_20180402_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='room_group_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_group_priority', to='tab.RoomGroup'),
        ),
        migrations.AddField(
            model_name='team',
            name='room_group_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_group_priorty', to='tab.RoomGroup'),
        ),
        migrations.AlterField(
            model_name='round',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tab.Room'),
        ),
    ]
