# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func_team(apps, schema_editor):
    MyModel = apps.get_model("tab", "Team")
    ContentType = apps.get_model("contenttypes", "ContentType")

    new_ct = ContentType.objects.get_for_model(MyModel)
    MyModel.objects.filter(polymorphic_ctype__isnull=True).update(
        polymorphic_ctype=new_ct)


def forwards_func_deb(apps, schema_editor):
    MyModel = apps.get_model("tab", "Debater")
    ContentType = apps.get_model("contenttypes", "ContentType")

    new_ct = ContentType.objects.get_for_model(MyModel)
    MyModel.objects.filter(polymorphic_ctype__isnull=True).update(
        polymorphic_ctype=new_ct)


def forwards_func(apps, schema_editor):
    forwards_func_deb(apps, schema_editor)
    forwards_func_team(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tab', '0007_auto_20190505_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_tab.debater_set+',
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='debater',
            name='tiebreaker',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_tab.team_set+',
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='team',
            name='tiebreaker',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
