# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tab', '0008_auto_20190520_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeCheckIn',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('round_number', models.IntegerField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='RoomCheckIn',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('polymorphic_ctype',
                 models.ForeignKey(
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='polymorphic_tab.roomcheckin_set+',
                     to='contenttypes.ContentType')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='judge',
        ),
        migrations.AlterModelOptions(
            name='debater',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.DeleteModel(name='CheckIn', ),
        migrations.AddField(
            model_name='roomcheckin',
            name='room',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='tab.Room'),
        ),
        migrations.AddField(
            model_name='judgecheckin',
            name='judge',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='tab.Judge'),
        ),
        migrations.AddField(
            model_name='judgecheckin',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_tab.judgecheckin_set+',
                to='contenttypes.ContentType'),
        ),
    ]
