# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-18 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0008_auto_20190520_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debater',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
