# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0008_auto_20180402_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rank',
        ),
    ]
