# Generated by Django 2.1.5 on 2019-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0010_auto_20191008_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='scratch',
            unique_together={('judge', 'team')},
        ),
    ]
