# Generated by Django 2.1.5 on 2019-10-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0010_auto_20191008_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Room')),
            ],
        ),
    ]
