# Generated by Django 2.1.5 on 2019-10-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_auto_20191013_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=-1)),
                ('type_of_team', models.IntegerField(choices=[(1, 'Varsity'), (0, 'Novice')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='broken',
        ),
        migrations.AddField(
            model_name='breakingteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Team'),
        ),
    ]
