# Generated by Django 2.1.5 on 2019-10-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_auto_20191012_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=-1)),
                ('effective_seed', models.IntegerField(default=-1)),
                ('type_of_team', models.IntegerField(
                    choices=[(0, 'Varsity'), (1, 'Novice')], default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='breaking_team', to='tab.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Outround',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('num_teams', models.IntegerField()),
                ('type_of_round', models.IntegerField(
                    choices=[(0, 'Varsity'), (1, 'Novice')], default=0)),
                ('victor', models.IntegerField(choices=[
                 (0, 'UNKNOWN'), (1, 'GOV'), (2, 'OPP'), (3, 'GOV via Forfeit'), (4, 'OPP via Forfeit')], default=0)),
                ('chair', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='chair_outround', to='tab.Judge')),
                ('gov_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='gov_team_outround', to='tab.Team')),
                ('judges', models.ManyToManyField(blank=True,
                 related_name='judges_outrounds', to='tab.Judge')),
                ('opp_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='opp_team_outround', to='tab.Team')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='rooms_outrounds', to='tab.Room')),
            ],
        ),
    ]
