# Generated by Django 2.1.5 on 2019-10-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_roomcheckin'),
        ('tab', '0011_auto_20191012_2018'),
    ]

    operations = [
    ]
