# Generated by Django 2.1.5 on 2019-10-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0012_merge_20191017_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratch',
            name='scratch_type',
            field=models.IntegerField(choices=[(0, 'Discretionary Scratch'), (1, 'Tab Scratch'), (2, 'School Scratch')]),
        ),
    ]
