# Generated by Django 2.1.5 on 2019-10-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0012_breakingteam_outround'),
        ('tab', '0011_roomcheckin'),
    ]

    operations = [
    ]
