# Generated by Django 2.1.5 on 2019-10-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0012_auto_20191013_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_teams', models.IntegerField()),
                ('type_of_round', models.IntegerField(choices=[(0, 'Varsity'), (1, 'Novice')], default=0)),
                ('victor', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'GOV'), (2, 'OPP'), (3, 'GOV via Forfeit'), (4, 'OPP via Forfeit')], default=0)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair_outround', to='tab.Judge')),
                ('gov_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gov_team_outround', to='tab.Team')),
                ('judges', models.ManyToManyField(blank=True, related_name='judges_outrounds', to='tab.Judge')),
                ('opp_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_team_outround', to='tab.Team')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Room')),
            ],
        ),
        migrations.AddField(
            model_name='breakingteam',
            name='effective_seed',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='type_of_team',
            field=models.IntegerField(choices=[(0, 'Varsity'), (1, 'Novice')], default=0),
        ),
    ]
