# Generated by Django 2.1.5 on 2019-11-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0012_merge_20191017_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='ballot_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
