# Generated by Django 2.1.5 on 2020-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0013_auto_20191122_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='discord_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='judge',
            name='discord_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='room',
            name='discord_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
