# Generated by Django 2.1.5 on 2019-10-13 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0013_auto_20191013_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='outround',
            name='losing_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_outrounds', to='tab.Team'),
        ),
        migrations.AddField(
            model_name='outround',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_outrounds', to='tab.Team'),
        ),
    ]
