# Generated by Django 2.1.5 on 2019-10-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0014_team_break_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='outround',
            name='sidelock',
            field=models.BooleanField(default=False),
        ),
    ]
