# Generated by Django 2.1.5 on 2020-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0014_auto_20200310_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='discord_id',
            new_name='text_channel_id',
        ),
        migrations.AddField(
            model_name='room',
            name='voice_channel_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
