# Generated by Django 2.1.5 on 2019-10-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0014_auto_20191013_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingteam',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breaking_team', to='tab.Team'),
        ),
    ]
