# Generated by Django 2.1.5 on 2019-10-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0015_auto_20191013_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outround',
            name='losing_team',
        ),
        migrations.RemoveField(
            model_name='outround',
            name='winning_team',
        ),
        migrations.AlterField(
            model_name='outround',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_outrounds', to='tab.Room'),
        ),
    ]
