# Generated by Django 2.1.5 on 2019-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0015_outround_sidelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='outround',
            name='choice',
            field=models.IntegerField(
                choices=[(0, 'Unknown'), (1, 'Gov'), (2, 'Opp')], default=0),
        ),
    ]
