# Generated by Django 2.1.5 on 2019-11-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0012_merge_20191017_0109'),
        ('tab', '0016_outround_choice'),
    ]

    operations = [
    ]
