# Generated by Django 2.1.5 on 2019-10-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_auto_20191012_2018'),
        ('tab', '0016_auto_20191014_1232'),
    ]

    operations = [
    ]
