# Generated by Django 2.1.5 on 2020-01-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0017_merge_20191106_1831'),
        ('tab', '0013_auto_20191122_0510'),
    ]

    operations = [
    ]
