# Generated by Django 2.2.10 on 2021-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0018_merge_20200124_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outround',
            name='choice',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Gov'), (2, 'Opp')], default=0),
        ),
    ]
