# Generated by Django 2.1.5 on 2020-05-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0018_merge_20200124_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outround',
            name='choice',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Gov'), (2, 'Opp')], default=0),
        ),
    ]
