# Generated by Django 2.2.16 on 2020-09-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0016_auto_20200321_0545'),
        ('tab', '0018_merge_20200124_1633'),
    ]

    operations = [
    ]
