# Generated by Django 2.2.10 on 2021-04-09 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0019_auto_20210408_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='debater',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='team',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='bye',
            name='bye_team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='byes', to='tab.Team'),
        ),
        migrations.AlterField(
            model_name='noshow',
            name='no_show_team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='no_shows', to='tab.Team'),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='judge',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='scratches', to='tab.Judge'),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='scratchs', to='tab.Team'),
        ),
    ]
