# Generated by Django 2.2.16 on 2020-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0019_merge_20200910_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outround',
            name='choice',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Gov'), (2, 'Opp')], default=0),
        ),
    ]
