# Generated by Django 2.2.16 on 2021-03-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0020_auto_20200910_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='rfd',
            field=models.TextField(blank=True),
        ),
    ]
