# Generated by Django 2.2.10 on 2023-11-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0020_auto_20210409_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratches', to='tab.Team'),
        ),
    ]
