# Generated by Django 2.2.10 on 2025-03-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0021_auto_20231104_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ranking_public',
            field=models.BooleanField(default=True),
        ),
    ]
