# Generated by Django 2.2.10 on 2025-02-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0021_auto_20231104_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tab.Room'),
        ),
    ]
