# Generated by Django 2.2.10 on 2022-02-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0020_auto_20210409_1938'),
        ('tab', '0021_round_rfd'),
    ]

    operations = [
    ]
