# Generated by Django 3.2.25 on 2025-08-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0021_auto_20231104_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='APDA_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='APDA_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
