# Generated by Django 3.2.25 on 2025-08-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0022_auto_20250227_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='apda_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='apda_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
