# Generated by Django 3.2.25 on 2025-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0022_auto_20250227_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='team',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
    ]
