# Generated by Django 3.2.25 on 2025-09-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0023_auto_20250809_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='wing_only',
            field=models.BooleanField(default=False),
        ),
    ]
