# Generated by Django 3.2.25 on 2025-09-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0024_judge_wing_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabsettings',
            name='key',
            field=models.CharField(max_length=25),
        ),
    ]
