# Generated by Django 3.2.25 on 2025-10-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0025_alter_tabsettings_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabsettings',
            name='value_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tabsettings',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tabsettings',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
