# Generated by Django 2.2.10 on 2025-10-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0025_alter_tabsettings_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='is_dino',
            field=models.BooleanField(default=False),
        ),
    ]
