# Generated by Django 2.2.10 on 2025-10-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0025_alter_tabsettings_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noshow',
            name='lenient_late',
        ),
    ]
