# Generated by Django 3.2.25 on 2025-10-12 21:26

from django.db import migrations, models


def create_accessible_roomtag(apps, schema_editor): 
    RoomTag = apps.get_model('tab', 'RoomTag') 
    RoomTag.objects.get_or_create(tag='Accessible', defaults={'priority': 99})

class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0026_judge_is_dino'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='required_room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='team',
            name='required_room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.RunPython(create_accessible_roomtag),
    ]
