# Generated by Django 3.2.25 on 2025-10-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0027_auto_20251012_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ranking_public',
            field=models.BooleanField(default=True),
        ),
    ]
