# Generated by Django 3.2.25 on 2025-10-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0030_auto_20251024_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noshow',
            name='lenient_late',
        ),
    ]
