# Generated by Django 3.2.25 on 2025-10-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0030_auto_20251024_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTeamScratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scratch_primary', to='tab.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scratch_secondary', to='tab.team')),
            ],
            options={
                'verbose_name_plural': 'team scratches',
                'unique_together': {('team_one', 'team_two')},
            },
        ),
        migrations.CreateModel(
            name='JudgeJudgeScratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scratch_primary', to='tab.judge')),
                ('judge_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scratch_secondary', to='tab.judge')),
            ],
            options={
                'verbose_name_plural': 'judge scratches',
                'unique_together': {('judge_one', 'judge_two')},
            },
        ),
    ]
