# Generated by Django 3.2.25 on 2025-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0031_remove_noshow_lenient_late'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualJudgeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=models.CASCADE, related_name='manual_round_assignments', to='tab.judge')),
                ('round', models.ForeignKey(on_delete=models.CASCADE, related_name='manual_judge_assignments', to='tab.round')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('round', 'judge')},
            },
        ),
    ]
