# Generated by Django 3.2.25 on 2025-11-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0031_remove_noshow_lenient_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
