# Generated by Django 3.2.25 on 2025-11-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('tab', '0031_remove_noshow_lenient_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debater',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tab.school'),
        ),
        migrations.AddField(
            model_name='judge',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='judge',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='registration.registration'),
        ),
        migrations.AddField(
            model_name='team',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='registration.registration'),
        ),
    ]
