# Generated by Django 3.2.25 on 2025-11-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0031_remove_noshow_lenient_late'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('debaters', models.ManyToManyField(blank=True, related_name='ranking_groups', to='tab.Debater')),
                ('teams', models.ManyToManyField(blank=True, related_name='ranking_groups', to='tab.Team')),
            ],
        ),
    ]
