# Generated by Django 3.2.25 on 2025-11-17 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0032_manualjudgeassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outround',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_outrounds', to='tab.room'),
        ),
    ]
