# Generated by Django 3.2.25 on 2025-11-14 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0032_manualjudgeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeExpectedCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_checkins', to='tab.judge')),
            ],
        ),
        migrations.AddConstraint(
            model_name='judgeexpectedcheckin',
            constraint=models.UniqueConstraint(fields=('judge', 'round_number'), name='unique_judge_expectation_per_round'),
        ),
    ]
