# Generated by Django 3.2.25 on 2025-11-14 21:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0032_manualjudgeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='ballot_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Ballot code must contain at least one letter on each side of a single hyphen.', regex='^[A-Za-z]+-[A-Za-z]+$')]),
        ),
        migrations.CreateModel(
            name='JudgeCodeEmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ballot_code', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_email_logs', to='tab.judge')),
            ],
        ),
        migrations.AddIndex(
            model_name='judgecodeemaillog',
            index=models.Index(fields=['email', 'sent_at'], name='tab_judgeco_email_4b0e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='judgecodeemaillog',
            index=models.Index(fields=['judge', 'sent_at'], name='tab_judgeco_judge_i_98bb44_idx'),
        ),
    ]
