# Generated by Django 3.2.25 on 2025-12-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0032_auto_20251111_2132'),
        ('tab', '0033_publicdisplaysetting'),
    ]

    operations = [
    ]
