# Generated by Django 3.2.25 on 2026-02-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0032_rankinggroup'),
        ('tab', '0034_add_motion_model'),
    ]

    operations = [
    ]
