# Generated by Django 3.2.25 on 2026-02-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tab", "0035_merge_0032_rankinggroup_0034_add_motion_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outround",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms_outrounds",
                to="tab.room",
            ),
        ),
    ]
