# pylint: disable=invalid-name
# Generated by Django 3.2.25 on 2026-03-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0032_judgejudgescratch_teamteamscratch'),
        ('tab', '0036_alter_outround_room_nullable'),
    ]

    operations = [
    ]
