# Generated by Django 3.2.25 on 2026-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0036_alter_outround_room_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='ranking_public',
            field=models.BooleanField(default=True),
        ),
    ]
