# Generated by Django 3.2.25 on 2026-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0037_judge_code_emailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
