# Generated by Django 3.2.25 on 2026-04-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tab", "0039_auto_20260424_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="rfd",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="WrittenRFDEmailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_rfd_email_logs",
                        to="tab.round",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="writtenrfdemaillog",
            index=models.Index(
                fields=["round", "sent_at"], name="tab_written_round_i_85db27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writtenrfdemaillog",
            index=models.Index(
                fields=["email", "sent_at"], name="tab_written_email_96131e_idx"
            ),
        ),
    ]
