# Generated by Django 3.2.25 on 2026-05-03 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0040_written_rfd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='ballot_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator(message='Ballot code must be legacy alphanumeric text or a hyphenated word-word code with an optional alphanumeric token.', regex='^(?:[A-Za-z]+-[A-Za-z]+(?:-[A-Za-z0-9]+)?|[A-Za-z0-9]+)$')]),
        ),
    ]
