# Generated by Django 3.2.25 on 2026-05-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tab", "0034_merge_20251220_2004"),
        ("tab", "0040_written_rfd"),
    ]

    operations = [
    ]
