# Generated by Django 3.2.25 on 2026-05-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tab", "0033_auto_20251114_2230"),
        ("tab", "0040_written_rfd"),
    ]

    operations = []
