# Generated by Django 3.2.25 on 2026-05-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tab", "0041_alter_judge_ballot_code"),
        ("tab", "0041_registration_roster_fields"),
    ]

    operations = []
