# Generated by Django 4.2.24 on 2026-05-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tab", "0041_merge_0033_auto_20251114_2230_0040_written_rfd"),
        ("tab", "0041_registration_roster_fields"),
    ]

    operations = []
