# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tab", "0045_merge_expected_checkins_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgecodeemaillog",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("registration", "Registration"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
