# Generated by Django 2.1.5 on 2020-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Completed')])),
            ],
        ),
    ]
